apiVersion: v2
name: valkey
description: A Helm chart for Valkey on Kubernetes

type: application

maintainers:
  - name: kienle1819
    url: https://github.com/kienle1819/helm-charts-applications

keywords:
  - cache
  - valkey

icon: https://valkey.io/img/Valkey-logo.svg

# This is the chart version
version: "2.0.0"

# This is the version number of the application being deployed.
appVersion: "8.0.1"
