apiVersion: v2
name: gitea
description: A Helm chart for Gitea on Kubernetes

type: application

maintainers:
  - name: kienle1819

# This is the chart version
version: "0.11.3"

# This is the version number of the application being deployed.
appVersion: "1.22.3"

dependencies:
  - name: mariadb
    version: "0.2.28"
    repository: "https://kienle1819.github.io/helm-charts-applications"
    condition: mariadb.enabled
  - name: postgres
    version: "0.2.26"
    repository: "https://kienle1819.github.io/helm-charts-applications"
    condition: postgres.enabled
  - name: redis
    version: "0.6.14"
    repository: "https://kienle1819.github.io/helm-charts-applications"
    condition: redis.enabled
