apiVersion: v2
name: ghost
description: A Helm chart for Ghost on Kubernetes

type: application

maintainers:
  - name: kienle1819

version: "0.140.1"

appVersion: "5.100.1"

dependencies:
  - name: mariadb
    version: "0.2.28"
    repository: "https://kienle1819.github.io/helm-charts-applications"
    condition: mariadb.enabled
  - name: mysql
    version: "0.2.0"
    repository: "https://kienle1819.github.io/helm-charts-applications"
    condition: mysql.enabled
