apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: kienle1819

version: "0.11.0"

appVersion: "6.3.1"

dependencies:
  - name: mongodb
    version: "0.6.8"
    repository: "https://kienle1819.github.io/helm-charts-applications"
    condition: mongodb.enabled
