apiVersion: v2
name: etcd
description: A Helm chart for etcd on Kubernetes

type: application

maintainers:
  - name: kienle1819
    url: https://github.com/kienle1819/helm-charts-applications

keywords:
  - database
  - etcd

icon: https://etcd.io/etcd-horizontal-white.png

version: "1.0.7"

appVersion: "v3.5.21"
